---
- name: Ensure gcc is installed
  package:
    name: gcc
    state: present

- name: Ensure java is installed
  package:
    name: java
    state: present

- name: Create Minecraft group
  group:
    name: minecraft
    state: present

- name: Setup Minecraft user
  user:
    name: minecraft
    system: true
    create_home: true
    home: /opt/minecraft
    shell: /bin/bash
    groups: minecraft
    state: present

- name: Create directories for Minecraft
  file:
    path: /opt/minecraft/{{ item }}
    state: directory
  loop:
    - tools
    - server
    - server/backups

- name: Clone mcrcon repository
  git:
    repo: https://github.com/Tiiffi/mcrcon.git
    dest: /opt/minecraft/tools/mcrcon

- name: Compile mcrcon
  command:
    cmd: gcc -std=gnu11 -pedantic -Wall -Wextra -O2 -s -o mcrcon mcrcon.c
  args:
    chdir: /opt/minecraft/tools/mcrcon