---
- name: Notify of backup start
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "say Starting Backup..."\015'
  register: backup_notify_result
  failed_when: 
    - backup_notify_result.rc != 0
    - '"No screen session found" not in backup_notify_result.stdout'
  tags:
    - always

- name: Stop saving
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "save-off"\015'
  register: stop_save_result
  failed_when: 
    - stop_save_result.rc != 0
    - '"No screen session found" not in stop_save_result.stdout'
  tags:
    - always

- name: Initiate save
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "save-all"\015'
  register: init_save_result
  failed_when: 
    - init_save_result.rc != 0
    - '"No screen session found" not in init_save_result.stdout'
  tags:
    - always

- name: Compress world directory
  archive:
    path: /opt/minecraft/server/world
    dest: /opt/minecraft/server/backups/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.zip
    format: zip
  tags:
    - always

- name: Start saving
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "save-on"\015'
  register: start_save_result
  failed_when: 
    - start_save_result.rc != 0
    - '"No screen session found" not in start_save_result.stdout'
  tags:
    - always

- name: Notify of backup finish
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "say Backup Complete"\015'
  register: backup_finish_notify_result
  failed_when: 
    - backup_finish_notify_result.rc != 0
    - '"No screen session found" not in backup_finish_notify_result.stdout'
  tags:
    - always