---
- name: Reload systemd to recognize the new service
  command: systemctl daemon-reload
  when: SERVICE_STATE == "enable"

- name: Enable Minecraft service
  systemd:
    name: minecraft
    enabled: yes
  when: SERVICE_STATE == "enable"

- name: Stop Minecraft service
  systemd:
    name: minecraft
    state: stopped
    ignore_errors: true
  when: SERVICE_STATE == "stop"  

- name: Start Minecraft service
  systemd:
    name: minecraft
    state: started
  when: SERVICE_STATE == "start" 