---
- name: Find all items in minecraft server directory (recursive)
  find:
    paths: /opt/minecraft/server/
    file_type: any
    recurse: yes
  register: server_contents
  tags:
    - always

- name: Delete modpack files except exclusions
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ server_contents.files }}"
  when: >
    '/opt/minecraft/server/backups' not in item.path and
    '/opt/minecraft/server/world' not in item.path and
    item.path not in excluded_files
  vars:
    excluded_files:
      - /opt/minecraft/server/eula.txt
      - /opt/minecraft/server/server.properties
      - /opt/minecraft/server/whitelist.json
      - /opt/minecraft/server/ops.json
  loop_control:
    label: "{{ item.path }}"
  tags:
    - always