---
- name: Get list of all files recursively
  find:
    path: /opt/minecraft/server/
    recurse: yes
  register: modpack_objects
  tags:
    - always

- name: Define list of paths to keep
  vars:
    keep_these:
      - /opt/minecraft/server/backups
      - /opt/minecraft/server/world
      - /opt/minecraft/server/eula.txt
      - /opt/minecraft/server/server.properties
      - /opt/minecraft/server/whitelist.json

- name: Delete all files and directories except exclusions
  file:
    path: "{{ item.path }}"
    state: absent
    recurse: true
  loop: "{{ modpack_objects.files }}"
  tags:
    - always
  when: item.path not in keep_these and not any(item.path.startswith(keep) for keep in keep_these)
