---
- name: Delete modpack files and directories except exclusions
  command: >
    find /opt/minecraft/server/ -mindepth 1 
    ! -path /opt/minecraft/server/backups
    ! -path /opt/minecraft/server/backups/*
    ! -path /opt/minecraft/server/world
    ! -path /opt/minecraft/server/world/*
    ! -path /opt/minecraft/server/eula.txt
    ! -path /opt/minecraft/server/server.properties
    ! -path /opt/minecraft/server/whitelist.json
    -exec rm -rf {} +
  args:
    warn: false
  tags:
    - always
