---
- name: Get list of all files recursively
  find:
    path: /opt/minecraft/server/
    recurse: yes
  register: modpack_objects
  tags:
    - always

- name: Delete all files and directories except exclusions
  file:
    path: "{{ item.path }}"
    state: absent
    recurse: true
  loop: "{{ modpack_objects.files }}"
  tags:
    - always
  when: item.path not in keep_these and item.path | none | match_any(keep_these)
